version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn clean package
      - echo $CODEBUILD_SRC_DIR
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - target/course_reviews_backend-0.0.1-SNAPSHOT.jar
    - discard-paths: yes