version: 0.2

phases:
  install:
    on-failure: ABORT | CONTINUE
    runtime-versions:
      java: corretto8
    commands:
      - echo install_java_runtime
  pre_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo pre_build
  build:
    on-failure: ABORT | CONTINUE
    commands:
      - mvn package
      - echo build
  post_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo post_build

artifacts:
  files:
    - target/course_reviews_backend-0.0.1-SNAPSHOT.jar